### ISSUE TITLE
How to change VOLTYPE to per- BAR?

### ISSUE THREAD

**Issue by tedmarcin** [AndrewAMD/SierraChartZorroPlugin#1]
In default settings (ZORRO TRADE MODE) , VOL TYPE is cumulative , how i can change them to VOL per BAR?
![Zorro SierraChart Plugin VOL](https://user-images.githubusercontent.com/11801361/106596061-cca5ac80-6554-11eb-9dec-9819081275d7.png)

**Comment by AndrewAMD** [comment]
In [Trade] mode (and therefore, via live market data feeds), Sierra Chart only offers session volume and not bar volume.  The requested feature will not implemented.
